services:
  - type: web
    name: eventify-events-platform
    env: node
    plan: free
    buildCommand: npm install && npm run build && npx prisma generate && npm run seed
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
